In [1]:
n_years = 5
years = [2022 - x for x in range(n_years)]

# Find locations with both temperature and precipitation data

In [2]:
import os
import pandas as pd

# 雨量
unique_stations = None
for year in years:
    df_precip = pd.read_csv(f'./雨量/{year}Precipitation.csv')
    station_names_set = set(df_precip['StationName'])
    
    if unique_stations is None:
        unique_stations = station_names_set
    else:
        unique_stations = unique_stations.intersection(station_names_set)
        
print("Unique Stations:\n", unique_stations)


# 氣溫
directory = './氣溫'
airtemp_folders = [d for d in os.listdir(directory) if os.path.isdir(os.path.join(directory, d))]
airtemp_folders.remove('.ipynb_checkpoints')
airtemp_folders.remove('data')

print("\nAir temperature stations:\n", airtemp_folders)


# 找交集
locations = list(unique_stations & set(airtemp_folders))
print("\nLocations:\n", locations)

Unique Stations:
 {'澎湖', '東吉島', '雲林', '馬祖', '成功', '屏東', '宜蘭', '臺中', '蘭嶼', '玉山', '彭佳嶼', '板橋', '苗栗', '日月潭', '高雄', '臺南', '基隆', '花蓮', '阿里山', '嘉義', '桃園', '新竹', '金門', '臺北', '恆春', '鞍部', '臺東', '彰化', '竹子湖', '新屋', '蘇澳', '淡水', '大武'}

Air temperature stations:
 ['臺北', '蘇澳', '竹子湖', '淡水', '玉山', '蘭嶼', '恆春', '臺中', '金門', '宜蘭', '新竹', '大武', '高雄', '板橋', '東吉島', '彭佳嶼', '日月潭', '成功', '臺南', '新屋', '澎湖', '花蓮', '阿里山', '基隆', '嘉義', '臺東', '鞍部', '馬祖']

Locations:
 ['澎湖', '東吉島', '馬祖', '成功', '宜蘭', '臺中', '蘭嶼', '玉山', '彭佳嶼', '板橋', '日月潭', '高雄', '臺南', '基隆', '花蓮', '阿里山', '嘉義', '新竹', '金門', '恆春', '臺北', '鞍部', '臺東', '竹子湖', '新屋', '蘇澳', '淡水', '大武']

NOTE: 剛好氣溫測站的資料就是交集，所以可以全部讀進來。

In [3]:
import pandas as pd


full_dataset_dict = dict()

for year in years:
    print(f'\n===================================== {year} =====================================\n')
    
    full_dataset = pd.DataFrame({})
    
    file_paths = [
        f'./雞蛋價格/eggPriceByDayCsv/{year}EggPriceByDay.csv', # 預測目標（y）
        f'./鴨蛋價格/duckEggPriceByDayCsv/{year}DuckEggPriceByDay.csv',
        f'./雞隻/{year}Chicken.csv',
        f'./雛雞/{year}ChickQuantity.csv',
        f'./進口飼料/{year}_Daily.csv',
    ]
    
    for file_path in file_paths:
        df = pd.read_csv(file_path)
        
        # sort date process
        if '雞蛋價格' in file_path or '鴨蛋價格' in file_path:
            df = df.sort_values(by='TransDate').reset_index(drop=True)
        if '進口飼料' in file_path:
            df = df.sort_values(by=['年', '月', '日']).reset_index(drop=True)
        if '雨量' in file_path or '雛雞' in file_path :
            df = df.sort_values(by='Date').reset_index(drop=True)
            
        full_dataset = pd.concat([full_dataset, df], axis=1)
        display(full_dataset)
        
        full_dataset_dict[year] = full_dataset

===================================== 2022 =====================================

      TransDate  egg_TaijinPrice
0    2022-01-01             34.5
1    2022-01-02             34.5
2    2022-01-03             34.5
3    2022-01-04             34.5
4    2022-01-05             34.5
..          ...              ...
360  2022-12-27             40.5
361  2022-12-28             40.5
362  2022-12-29             40.5
363  2022-12-30             40.5
364  2022-12-31             40.5

[365 rows x 2 columns]

      TransDate  egg_TaijinPrice   TransDate Duckegg_TNN_TaijinPrice
0    2022-01-01             34.5  2022-01-01                    38.0
1    2022-01-02             34.5  2022-01-02                    38.0
2    2022-01-03             34.5  2022-01-03                    38.0
3    2022-01-04             34.5  2022-01-04                    38.0
4    2022-01-05             34.5  2022-01-05                    38.0
..          ...              ...         ...                     ...
360  2022-12-27             40.5  2022-12-27                    43.0
361  2022-12-28             40.5  2022-12-28                    43.0
362  2022-12-29             40.5  2022-12-29                    43.0
363  2022-12-30             40.5  2022-12-30                    43.0
364  2022-12-31             40.5  2022-12-31                    43.0

[365 rows x 4 columns]

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數
0,2022-01-01,34.5,2022-01-01,38.0,2022-01-01,1568627.0,32028103.0,114774.0,1583271.0,1789780.0
1,2022-01-02,34.5,2022-01-02,38.0,2022-01-02,1568627.0,32028103.0,114774.0,1583271.0,1789780.0
2,2022-01-03,34.5,2022-01-03,38.0,2022-01-03,1568627.0,32028103.0,114774.0,1583271.0,1789780.0
3,2022-01-04,34.5,2022-01-04,38.0,2022-01-04,1568627.0,32028103.0,114774.0,1583271.0,1789780.0
4,2022-01-05,34.5,2022-01-05,38.0,2022-01-05,1568627.0,32028103.0,114774.0,1583271.0,1789780.0
...,...,...,...,...,...,...,...,...,...,...
360,2022-12-27,40.5,2022-12-27,43.0,2022-12-27,1592549.0,35037318.0,122636.0,1203140.0,990135.0
361,2022-12-28,40.5,2022-12-28,43.0,2022-12-28,1592549.0,35037318.0,122636.0,1203140.0,990135.0
362,2022-12-29,40.5,2022-12-29,43.0,2022-12-29,1592549.0,35037318.0,122636.0,1203140.0,990135.0
363,2022-12-30,40.5,2022-12-30,43.0,2022-12-30,1592549.0,35037318.0,122636.0,1203140.0,990135.0
364,2022-12-31,40.5,2022-12-31,43.0,2022-12-31,1592549.0,35037318.0,122636.0,1203140.0,990135.0

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity
0,2022-01-01,34.5,2022-01-01,38.0,2022-01-01,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN
1,2022-01-02,34.5,2022-01-02,38.0,2022-01-02,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN
2,2022-01-03,34.5,2022-01-03,38.0,2022-01-03,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN
3,2022-01-04,34.5,2022-01-04,38.0,2022-01-04,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN
4,2022-01-05,34.5,2022-01-05,38.0,2022-01-05,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2022-12-27,40.5,2022-12-27,43.0,2022-12-27,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN
361,2022-12-28,40.5,2022-12-28,43.0,2022-12-28,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN
362,2022-12-29,40.5,2022-12-29,43.0,2022-12-29,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN
363,2022-12-30,40.5,2022-12-30,43.0,2022-12-30,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN
364,2022-12-31,40.5,2022-12-31,43.0,2022-12-31,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,...,RedChickQuantity,ImportChickenQuantity,年,月,日,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,2022-01-01,34.5,2022-01-01,38.0,2022-01-01,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,...,60720,NaN,2022,1,1,15.45,16.0,15.15,20.9,17.90
1,2022-01-02,34.5,2022-01-02,38.0,2022-01-02,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,...,60720,NaN,2022,1,2,15.45,16.7,15.35,20.9,17.90
2,2022-01-03,34.5,2022-01-03,38.0,2022-01-03,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,...,60720,NaN,2022,1,3,15.45,16.0,15.15,20.9,17.90
3,2022-01-04,34.5,2022-01-04,38.0,2022-01-04,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,...,60720,NaN,2022,1,4,15.45,16.7,15.35,20.9,17.90
4,2022-01-05,34.5,2022-01-05,38.0,2022-01-05,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,...,60720,NaN,2022,1,5,15.40,17.1,15.50,20.9,18.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2022-12-27,40.5,2022-12-27,43.0,2022-12-27,1592549.0,35037318.0,122636.0,1203140.0,990135.0,...,83670,NaN,2022,12,27,10.85,19.9,11.60,21.1,21.00
361,2022-12-28,40.5,2022-12-28,43.0,2022-12-28,1592549.0,35037318.0,122636.0,1203140.0,990135.0,...,83670,NaN,2022,12,28,11.05,19.9,11.68,21.1,21.00
362,2022-12-29,40.5,2022-12-29,43.0,2022-12-29,1592549.0,35037318.0,122636.0,1203140.0,990135.0,...,91500,NaN,2022,12,29,11.05,19.9,11.78,21.1,21.00
363,2022-12-30,40.5,2022-12-30,43.0,2022-12-30,1592549.0,35037318.0,122636.0,1203140.0,990135.0,...,91500,NaN,2022,12,30,11.20,19.9,11.78,21.1,21.00
364,2022-12-31,40.5,2022-12-31,43.0,2022-12-31,1592549.0,35037318.0,122636.0,1203140.0,990135.0,...,91500,NaN,2022,12,31,11.20,19.9,11.78,21.1,21.00

===================================== 2021 =====================================

      TransDate egg_TaijinPrice
0    2021-01-01            24.5
1    2021-01-02            24.5
2    2021-01-03            24.5
3    2021-01-04            24.5
4    2021-01-05            24.5
..          ...             ...
360  2021-12-27            34.5
361  2021-12-28            34.5
362  2021-12-29            34.5
363  2021-12-30            34.5
364  2021-12-31            34.5

[365 rows x 2 columns]

      TransDate egg_TaijinPrice   TransDate Duckegg_TNN_TaijinPrice
0    2021-01-01            24.5  2021-01-01                    32.0
1    2021-01-02            24.5  2021-01-02                    32.0
2    2021-01-03            24.5  2021-01-03                    32.0
3    2021-01-04            24.5  2021-01-04                    32.0
4    2021-01-05            24.5  2021-01-05                    32.0
..          ...             ...         ...                     ...
360  2021-12-27            34.5  2021-12-27                    38.0
361  2021-12-28            34.5  2021-12-28                    38.0
362  2021-12-29            34.5  2021-12-29                    38.0
363  2021-12-30            34.5  2021-12-30                    38.0
364  2021-12-31            34.5  2021-12-31                    38.0

[365 rows x 4 columns]

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數
0,2021-01-01,24.5,2021-01-01,32.0,2021-01-01,1247145.0,33548211.0,121875.0,1331541.0,958692.0
1,2021-01-02,24.5,2021-01-02,32.0,2021-01-02,1247145.0,33548211.0,121875.0,1331541.0,958692.0
2,2021-01-03,24.5,2021-01-03,32.0,2021-01-03,1247145.0,33548211.0,121875.0,1331541.0,958692.0
3,2021-01-04,24.5,2021-01-04,32.0,2021-01-04,1247145.0,33548211.0,121875.0,1331541.0,958692.0
4,2021-01-05,24.5,2021-01-05,32.0,2021-01-05,1247145.0,33548211.0,121875.0,1331541.0,958692.0
...,...,...,...,...,...,...,...,...,...,...
360,2021-12-27,34.5,2021-12-27,38.0,2021-12-27,1508459.0,33574033.0,122899.0,1211918.0,715929.0
361,2021-12-28,34.5,2021-12-28,38.0,2021-12-28,1508459.0,33574033.0,122899.0,1211918.0,715929.0
362,2021-12-29,34.5,2021-12-29,38.0,2021-12-29,1508459.0,33574033.0,122899.0,1211918.0,715929.0
363,2021-12-30,34.5,2021-12-30,38.0,2021-12-30,1508459.0,33574033.0,122899.0,1211918.0,715929.0
364,2021-12-31,34.5,2021-12-31,38.0,2021-12-31,1508459.0,33574033.0,122899.0,1211918.0,715929.0

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity
0,2021-01-01,24.5,2021-01-01,32.0,2021-01-01,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0
1,2021-01-02,24.5,2021-01-02,32.0,2021-01-02,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0
2,2021-01-03,24.5,2021-01-03,32.0,2021-01-03,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0
3,2021-01-04,24.5,2021-01-04,32.0,2021-01-04,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0
4,2021-01-05,24.5,2021-01-05,32.0,2021-01-05,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2021-12-27,34.5,2021-12-27,38.0,2021-12-27,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN
361,2021-12-28,34.5,2021-12-28,38.0,2021-12-28,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN
362,2021-12-29,34.5,2021-12-29,38.0,2021-12-29,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN
363,2021-12-30,34.5,2021-12-30,38.0,2021-12-30,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN
364,2021-12-31,34.5,2021-12-31,38.0,2021-12-31,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,...,RedChickQuantity,ImportChickenQuantity,年,月,日,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,2021-01-01,24.5,2021-01-01,32.0,2021-01-01,1247145.0,33548211.0,121875.0,1331541.0,958692.0,...,88600,35940.0,2021,1,1,8.3,16.0,8.35,17.2,17.25
1,2021-01-02,24.5,2021-01-02,32.0,2021-01-02,1247145.0,33548211.0,121875.0,1331541.0,958692.0,...,88600,35940.0,2021,1,2,8.3,16.0,8.35,17.2,17.25
2,2021-01-03,24.5,2021-01-03,32.0,2021-01-03,1247145.0,33548211.0,121875.0,1331541.0,958692.0,...,88600,35940.0,2021,1,3,8.3,16.0,8.35,17.2,17.25
3,2021-01-04,24.5,2021-01-04,32.0,2021-01-04,1247145.0,33548211.0,121875.0,1331541.0,958692.0,...,88600,35940.0,2021,1,4,8.3,16.0,8.35,17.2,17.25
4,2021-01-05,24.5,2021-01-05,32.0,2021-01-05,1247145.0,33548211.0,121875.0,1331541.0,958692.0,...,88600,35940.0,2021,1,5,8.5,16.2,8.50,17.2,17.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2021-12-27,34.5,2021-12-27,38.0,2021-12-27,1508459.0,33574033.0,122899.0,1211918.0,715929.0,...,52913,NaN,2021,12,27,14.2,16.3,14.45,20.9,17.50
361,2021-12-28,34.5,2021-12-28,38.0,2021-12-28,1508459.0,33574033.0,122899.0,1211918.0,715929.0,...,52913,NaN,2021,12,28,14.3,16.5,14.55,20.9,17.70
362,2021-12-29,34.5,2021-12-29,38.0,2021-12-29,1508459.0,33574033.0,122899.0,1211918.0,715929.0,...,52913,NaN,2021,12,29,14.5,16.7,14.65,20.9,17.90
363,2021-12-30,34.5,2021-12-30,38.0,2021-12-30,1508459.0,33574033.0,122899.0,1211918.0,715929.0,...,52913,NaN,2021,12,30,14.8,16.7,14.85,20.9,17.90
364,2021-12-31,34.5,2021-12-31,38.0,2021-12-31,1508459.0,33574033.0,122899.0,1211918.0,715929.0,...,52913,NaN,2021,12,31,14.8,16.7,14.85,20.9,17.90

===================================== 2020 =====================================

      TransDate  egg_TaijinPrice
0    2020-01-01             27.5
1    2020-01-02             27.5
2    2020-01-03             27.5
3    2020-01-04             27.5
4    2020-01-05             27.5
..          ...              ...
361  2020-12-27             24.5
362  2020-12-28             24.5
363  2020-12-29             24.5
364  2020-12-30             24.5
365  2020-12-31             24.5

[366 rows x 2 columns]

      TransDate  egg_TaijinPrice   TransDate  Duckegg_TNN_TaijinPrice
0    2020-01-01             27.5  2020-01-01                     34.0
1    2020-01-02             27.5  2020-01-02                     34.0
2    2020-01-03             27.5  2020-01-03                     34.0
3    2020-01-04             27.5  2020-01-04                     34.0
4    2020-01-05             27.5  2020-01-05                     34.0
..          ...              ...         ...                      ...
361  2020-12-27             24.5  2020-12-27                     32.0
362  2020-12-28             24.5  2020-12-28                     32.0
363  2020-12-29             24.5  2020-12-29                     32.0
364  2020-12-30             24.5  2020-12-30                     32.0
365  2020-12-31             24.5  2020-12-31                     32.0

[366 rows x 4 columns]

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數
0,2020-01-01,27.5,2020-01-01,34.0,2020-01-01,1358328.0,30532400.0,112185.0,1403613.0,2684624.0
1,2020-01-02,27.5,2020-01-02,34.0,2020-01-02,1358328.0,30532400.0,112185.0,1403613.0,2684624.0
2,2020-01-03,27.5,2020-01-03,34.0,2020-01-03,1358328.0,30532400.0,112185.0,1403613.0,2684624.0
3,2020-01-04,27.5,2020-01-04,34.0,2020-01-04,1358328.0,30532400.0,112185.0,1403613.0,2684624.0
4,2020-01-05,27.5,2020-01-05,34.0,2020-01-05,1358328.0,30532400.0,112185.0,1403613.0,2684624.0
...,...,...,...,...,...,...,...,...,...,...
361,2020-12-27,24.5,2020-12-27,32.0,2020-12-27,1407936.0,33803767.0,124295.0,1100058.0,791242.0
362,2020-12-28,24.5,2020-12-28,32.0,2020-12-28,1407936.0,33803767.0,124295.0,1100058.0,791242.0
363,2020-12-29,24.5,2020-12-29,32.0,2020-12-29,1407936.0,33803767.0,124295.0,1100058.0,791242.0
364,2020-12-30,24.5,2020-12-30,32.0,2020-12-30,1407936.0,33803767.0,124295.0,1100058.0,791242.0
365,2020-12-31,24.5,2020-12-31,32.0,2020-12-31,1407936.0,33803767.0,124295.0,1100058.0,791242.0

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity
0,2020-01-01,27.5,2020-01-01,34.0,2020-01-01,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0
1,2020-01-02,27.5,2020-01-02,34.0,2020-01-02,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0
2,2020-01-03,27.5,2020-01-03,34.0,2020-01-03,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0
3,2020-01-04,27.5,2020-01-04,34.0,2020-01-04,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0
4,2020-01-05,27.5,2020-01-05,34.0,2020-01-05,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2020-12-27,24.5,2020-12-27,32.0,2020-12-27,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0
362,2020-12-28,24.5,2020-12-28,32.0,2020-12-28,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0
363,2020-12-29,24.5,2020-12-29,32.0,2020-12-29,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0
364,2020-12-30,24.5,2020-12-30,32.0,2020-12-30,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0
365,2020-12-31,24.5,2020-12-31,32.0,2020-12-31,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,...,RedChickQuantity,ImportChickenQuantity,年,月,日,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,2020-01-01,27.5,2020-01-01,34.0,2020-01-01,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,...,84500,20385.0,2020,1,1,6.90,12.6,7.28,13.7,13.65
1,2020-01-02,27.5,2020-01-02,34.0,2020-01-02,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,...,84500,20385.0,2020,1,2,6.90,12.6,7.28,13.7,13.65
2,2020-01-03,27.5,2020-01-03,34.0,2020-01-03,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,...,84500,20385.0,2020,1,3,6.90,12.6,7.28,13.7,13.65
3,2020-01-04,27.5,2020-01-04,34.0,2020-01-04,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,...,84500,20385.0,2020,1,4,6.90,12.6,7.28,13.7,13.65
4,2020-01-05,27.5,2020-01-05,34.0,2020-01-05,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,...,84500,20385.0,2020,1,5,6.90,12.6,7.28,13.7,13.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2020-12-27,24.5,2020-12-27,32.0,2020-12-27,1407936.0,33803767.0,124295.0,1100058.0,791242.0,...,69200,33498.0,2020,12,27,7.85,15.4,8.28,16.6,16.66
362,2020-12-28,24.5,2020-12-28,32.0,2020-12-28,1407936.0,33803767.0,124295.0,1100058.0,791242.0,...,69200,33498.0,2020,12,28,7.85,15.4,8.28,16.6,16.66
363,2020-12-29,24.5,2020-12-29,32.0,2020-12-29,1407936.0,33803767.0,124295.0,1100058.0,791242.0,...,69200,33498.0,2020,12,29,7.90,15.6,8.28,16.8,16.66
364,2020-12-30,24.5,2020-12-30,32.0,2020-12-30,1407936.0,33803767.0,124295.0,1100058.0,791242.0,...,69200,33498.0,2020,12,30,8.00,15.8,8.28,17.0,16.76
365,2020-12-31,24.5,2020-12-31,32.0,2020-12-31,1407936.0,33803767.0,124295.0,1100058.0,791242.0,...,69200,33498.0,2020,12,31,8.00,15.8,NaN,17.0,16.95

===================================== 2019 =====================================

      TransDate  egg_TaijinPrice
0    2019-01-01             33.5
1    2019-01-02             33.5
2    2019-01-03             33.5
3    2019-01-04             33.5
4    2019-01-05             33.5
..          ...              ...
360  2019-12-27             27.5
361  2019-12-28             27.5
362  2019-12-29             27.5
363  2019-12-30             27.5
364  2019-12-31             27.5

[365 rows x 2 columns]

      TransDate  egg_TaijinPrice   TransDate  Duckegg_TNN_TaijinPrice
0    2019-01-01             33.5  2019-01-01                     34.0
1    2019-01-02             33.5  2019-01-02                     34.0
2    2019-01-03             33.5  2019-01-03                     34.0
3    2019-01-04             33.5  2019-01-04                     34.0
4    2019-01-05             33.5  2019-01-05                     34.0
..          ...              ...         ...                      ...
360  2019-12-27             27.5  2019-12-27                     34.0
361  2019-12-28             27.5  2019-12-28                     34.0
362  2019-12-29             27.5  2019-12-29                     34.0
363  2019-12-30             27.5  2019-12-30                     34.0
364  2019-12-31             27.5  2019-12-31                     34.0

[365 rows x 4 columns]

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數
0,2019-01-01,33.5,2019-01-01,34.0,2019-01-01,1751620.0,28287430.0,94427.0,1549147.0,1380962.0
1,2019-01-02,33.5,2019-01-02,34.0,2019-01-02,1751620.0,28287430.0,94427.0,1549147.0,1380962.0
2,2019-01-03,33.5,2019-01-03,34.0,2019-01-03,1751620.0,28287430.0,94427.0,1549147.0,1380962.0
3,2019-01-04,33.5,2019-01-04,34.0,2019-01-04,1751620.0,28287430.0,94427.0,1549147.0,1380962.0
4,2019-01-05,33.5,2019-01-05,34.0,2019-01-05,1751620.0,28287430.0,94427.0,1549147.0,1380962.0
...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,27.5,2019-12-27,34.0,2019-12-27,1209823.0,32805865.0,120704.0,934644.0,790006.0
361,2019-12-28,27.5,2019-12-28,34.0,2019-12-28,1209823.0,32805865.0,120704.0,934644.0,790006.0
362,2019-12-29,27.5,2019-12-29,34.0,2019-12-29,1209823.0,32805865.0,120704.0,934644.0,790006.0
363,2019-12-30,27.5,2019-12-30,34.0,2019-12-30,1209823.0,32805865.0,120704.0,934644.0,790006.0
364,2019-12-31,27.5,2019-12-31,34.0,2019-12-31,1209823.0,32805865.0,120704.0,934644.0,790006.0

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity
0,2019-01-01,33.5,2019-01-01,34.0,2019-01-01,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701
1,2019-01-02,33.5,2019-01-02,34.0,2019-01-02,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701
2,2019-01-03,33.5,2019-01-03,34.0,2019-01-03,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701
3,2019-01-04,33.5,2019-01-04,34.0,2019-01-04,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701
4,2019-01-05,33.5,2019-01-05,34.0,2019-01-05,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,27.5,2019-12-27,34.0,2019-12-27,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000
361,2019-12-28,27.5,2019-12-28,34.0,2019-12-28,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000
362,2019-12-29,27.5,2019-12-29,34.0,2019-12-29,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000
363,2019-12-30,27.5,2019-12-30,34.0,2019-12-30,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000
364,2019-12-31,27.5,2019-12-31,34.0,2019-12-31,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,...,RedChickQuantity,ImportChickenQuantity,年,月,日,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,2019-01-01,33.5,2019-01-01,34.0,2019-01-01,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,...,35800,35701,2019,1,1,7.40,12.30,7.93,13.50,13.44
1,2019-01-02,33.5,2019-01-02,34.0,2019-01-02,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,...,35800,35701,2019,1,2,7.40,12.30,7.93,13.50,13.44
2,2019-01-03,33.5,2019-01-03,34.0,2019-01-03,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,...,35800,35701,2019,1,3,7.35,12.30,7.90,13.50,13.45
3,2019-01-04,33.5,2019-01-04,34.0,2019-01-04,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,...,35800,35701,2019,1,4,7.35,12.30,7.87,13.50,13.45
4,2019-01-05,33.5,2019-01-05,34.0,2019-01-05,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,...,35800,35701,2019,1,5,7.35,12.30,7.87,13.50,13.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,27.5,2019-12-27,34.0,2019-12-27,1209823.0,32805865.0,120704.0,934644.0,790006.0,...,112000,29000,2019,12,27,6.88,12.65,7.26,13.75,13.68
361,2019-12-28,27.5,2019-12-28,34.0,2019-12-28,1209823.0,32805865.0,120704.0,934644.0,790006.0,...,112000,29000,2019,12,28,6.88,12.65,7.26,13.75,13.68
362,2019-12-29,27.5,2019-12-29,34.0,2019-12-29,1209823.0,32805865.0,120704.0,934644.0,790006.0,...,112000,29000,2019,12,29,6.90,12.60,7.26,13.70,13.65
363,2019-12-30,27.5,2019-12-30,34.0,2019-12-30,1209823.0,32805865.0,120704.0,934644.0,790006.0,...,112000,29000,2019,12,30,6.90,12.60,7.26,13.70,13.65
364,2019-12-31,27.5,2019-12-31,34.0,2019-12-31,1209823.0,32805865.0,120704.0,934644.0,790006.0,...,112000,29000,2019,12,31,6.90,12.60,7.26,13.70,13.65

===================================== 2018 =====================================

      TransDate  egg_TaijinPrice
0    2018-01-01             24.5
1    2018-01-02             24.5
2    2018-01-03             26.5
3    2018-01-04             26.5
4    2018-01-05             26.5
..          ...              ...
360  2018-12-27             33.5
361  2018-12-28             33.5
362  2018-12-29             33.5
363  2018-12-30             33.5
364  2018-12-31             33.5

[365 rows x 2 columns]

      TransDate  egg_TaijinPrice   TransDate Duckegg_TNN_TaijinPrice
0    2018-01-01             24.5  2018-01-01                    34.0
1    2018-01-02             24.5  2018-01-02                    34.0
2    2018-01-03             26.5  2018-01-03                    34.0
3    2018-01-04             26.5  2018-01-04                    34.0
4    2018-01-05             26.5  2018-01-05                    34.0
..          ...              ...         ...                     ...
360  2018-12-27             33.5  2018-12-27                    34.0
361  2018-12-28             33.5  2018-12-28                    34.0
362  2018-12-29             33.5  2018-12-29                    34.0
363  2018-12-30             33.5  2018-12-30                    34.0
364  2018-12-31             33.5  2018-12-31                    34.0

[365 rows x 4 columns]

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數
0,2018-01-01,24.5,2018-01-01,34.0,2018-01-01,1160830.0,31170982.0,114908.0,866824.0,633700.0
1,2018-01-02,24.5,2018-01-02,34.0,2018-01-02,1160830.0,31170982.0,114908.0,866824.0,633700.0
2,2018-01-03,26.5,2018-01-03,34.0,2018-01-03,1160830.0,31170982.0,114908.0,866824.0,633700.0
3,2018-01-04,26.5,2018-01-04,34.0,2018-01-04,1160830.0,31170982.0,114908.0,866824.0,633700.0
4,2018-01-05,26.5,2018-01-05,34.0,2018-01-05,1160830.0,31170982.0,114908.0,866824.0,633700.0
...,...,...,...,...,...,...,...,...,...,...
360,2018-12-27,33.5,2018-12-27,34.0,2018-12-27,1265184.0,29069345.0,94794.0,922436.0,893790.0
361,2018-12-28,33.5,2018-12-28,34.0,2018-12-28,1265184.0,29069345.0,94794.0,922436.0,893790.0
362,2018-12-29,33.5,2018-12-29,34.0,2018-12-29,1265184.0,29069345.0,94794.0,922436.0,893790.0
363,2018-12-30,33.5,2018-12-30,34.0,2018-12-30,1265184.0,29069345.0,94794.0,922436.0,893790.0
364,2018-12-31,33.5,2018-12-31,34.0,2018-12-31,1265184.0,29069345.0,94794.0,922436.0,893790.0

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity
0,2018-01-01,24.5,2018-01-01,34.0,2018-01-01,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0
1,2018-01-02,24.5,2018-01-02,34.0,2018-01-02,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0
2,2018-01-03,26.5,2018-01-03,34.0,2018-01-03,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0
3,2018-01-04,26.5,2018-01-04,34.0,2018-01-04,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0
4,2018-01-05,26.5,2018-01-05,34.0,2018-01-05,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2018-12-27,33.5,2018-12-27,34.0,2018-12-27,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0
361,2018-12-28,33.5,2018-12-28,34.0,2018-12-28,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0
362,2018-12-29,33.5,2018-12-29,34.0,2018-12-29,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0
363,2018-12-30,33.5,2018-12-30,34.0,2018-12-30,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0
364,2018-12-31,33.5,2018-12-31,34.0,2018-12-31,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0

,TransDate,egg_TaijinPrice,TransDate,Duckegg_TNN_TaijinPrice,月份,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,...,RedChickQuantity,ImportChickenQuantity,年,月,日,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,2018-01-01,24.5,2018-01-01,34.0,2018-01-01,1160830.0,31170982.0,114908.0,866824.0,633700.0,...,84800,0,2018,1,1,6.1,12.15,6.65,13.30,13.21
1,2018-01-02,24.5,2018-01-02,34.0,2018-01-02,1160830.0,31170982.0,114908.0,866824.0,633700.0,...,84800,0,2018,1,2,6.1,12.15,6.65,13.30,13.21
2,2018-01-03,26.5,2018-01-03,34.0,2018-01-03,1160830.0,31170982.0,114908.0,866824.0,633700.0,...,84800,0,2018,1,3,6.1,12.15,6.65,13.30,13.21
3,2018-01-04,26.5,2018-01-04,34.0,2018-01-04,1160830.0,31170982.0,114908.0,866824.0,633700.0,...,84800,0,2018,1,4,6.1,12.15,6.63,13.30,13.21
4,2018-01-05,26.5,2018-01-05,34.0,2018-01-05,1160830.0,31170982.0,114908.0,866824.0,633700.0,...,84800,0,2018,1,5,6.1,12.15,6.63,13.30,13.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2018-12-27,33.5,2018-12-27,34.0,2018-12-27,1265184.0,29069345.0,94794.0,922436.0,893790.0,...,52800,0,2018,12,27,7.4,12.35,7.98,13.55,13.41
361,2018-12-28,33.5,2018-12-28,34.0,2018-12-28,1265184.0,29069345.0,94794.0,922436.0,893790.0,...,52800,0,2018,12,28,7.4,12.35,7.95,13.55,13.41
362,2018-12-29,33.5,2018-12-29,34.0,2018-12-29,1265184.0,29069345.0,94794.0,922436.0,893790.0,...,39900,0,2018,12,29,7.4,12.35,7.95,13.55,13.41
363,2018-12-30,33.5,2018-12-30,34.0,2018-12-30,1265184.0,29069345.0,94794.0,922436.0,893790.0,...,39900,0,2018,12,30,7.4,12.35,7.95,13.55,13.41
364,2018-12-31,33.5,2018-12-31,34.0,2018-12-31,1265184.0,29069345.0,94794.0,922436.0,893790.0,...,39900,0,2018,12,31,7.4,12.35,7.95,13.55,13.41

# Classify by locations(temperature and precipitation)

In [4]:
full_dataset_by_year_location_dict = dict()

for year in years:    
    print(f'\n===================================== {year} =====================================\n')
    df = full_dataset_dict[year]
    df = df.drop(columns=['TransDate', '月份', '年', '月', '日'])
    
    
    dataset_location = dict()
    
    for location in locations:
        full_dataset_by_location = df.copy(deep=True)
        
        df_temp = pd.read_csv(f'./氣溫/{location}/{year}AirTemperature.csv')
        df_temp = df_temp.drop(columns=['AirTemperatureMaxDate'])
        
        df_prec = pd.read_csv(f'./雨量/{year}Precipitation.csv')
        df_prec = df_prec[df_prec['StationName'] == location].drop(columns=['StationName', 'Date'])
        df_prec = df_prec.reset_index(drop=True)
        
        
        full_dataset_by_location = pd.concat([full_dataset_by_location, df_temp], axis=1)
        full_dataset_by_location = pd.concat([full_dataset_by_location, df_prec], axis=1)

        """ special case handling """
        # handle special case 2022 高雄, column 'Precipitation'
        if year == 2022 and location == '高雄':
            full_dataset_by_location = full_dataset_by_location.dropna(subset=['Precipitation'])
                
        dataset_location[location] = full_dataset_by_location
        
    full_dataset_by_year_location_dict[year] = dataset_location

===================================== 2022 =====================================

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,澎湖,18.0,22.1,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,澎湖,18.0,22.1,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,澎湖,18.0,22.1,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,澎湖,18.0,22.1,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,澎湖,18.0,22.1,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,澎湖,18.1,22.1,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,澎湖,18.1,22.1,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,澎湖,18.1,22.1,0.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,澎湖,18.1,22.1,T
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,澎湖,18.1,22.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,東吉島,19.0,22.6,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,東吉島,19.0,22.6,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,東吉島,19.0,22.6,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,東吉島,19.0,22.6,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,東吉島,19.0,22.6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,東吉島,18.9,22.8,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,東吉島,18.9,22.8,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,東吉島,18.9,22.8,0.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,東吉島,18.9,22.8,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,東吉島,18.9,22.8,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,馬祖,11.0,17.6,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,馬祖,11.0,17.6,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,馬祖,11.0,17.6,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,馬祖,11.0,17.6,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,馬祖,11.0,17.6,15.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,馬祖,11.9,19.4,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,馬祖,11.9,19.4,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,馬祖,11.9,19.4,0.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,馬祖,11.9,19.4,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,馬祖,11.9,19.4,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,成功,19.3,26.4,1.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,成功,19.3,26.4,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,成功,19.3,26.4,T
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,成功,19.3,26.4,0.5
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,成功,19.3,26.4,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,成功,20.3,29.7,0.5
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,成功,20.3,29.7,0.5
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,成功,20.3,29.7,1.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,成功,20.3,29.7,0.5
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,成功,20.3,29.7,2.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,宜蘭,17.1,25.3,T
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,宜蘭,17.1,25.3,T
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,宜蘭,17.1,25.3,T
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,宜蘭,17.1,25.3,7.5
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,宜蘭,17.1,25.3,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,宜蘭,16.7,28.0,T
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,宜蘭,16.7,28.0,25.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,宜蘭,16.7,28.0,13.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,宜蘭,16.7,28.0,1.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,宜蘭,16.7,28.0,69.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,臺中,17.9,27.6,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,臺中,17.9,27.6,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,臺中,17.9,27.6,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,臺中,17.9,27.6,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,臺中,17.9,27.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,臺中,17.8,28.1,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,臺中,17.8,28.1,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,臺中,17.8,28.1,T
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,臺中,17.8,28.1,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,臺中,17.8,28.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,蘭嶼,19.0,23.6,11.5
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,蘭嶼,19.0,23.6,27.5
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,蘭嶼,19.0,23.6,16.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,蘭嶼,19.0,23.6,20.5
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,蘭嶼,19.0,23.6,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,蘭嶼,19.2,24.8,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,蘭嶼,19.2,24.8,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,蘭嶼,19.2,24.8,18.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,蘭嶼,19.2,24.8,10.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,蘭嶼,19.2,24.8,1.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,玉山,0.4,12.7,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,玉山,0.4,12.7,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,玉山,0.4,12.7,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,玉山,0.4,12.7,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,玉山,0.4,12.7,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,玉山,2.2,16.3,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,玉山,2.2,16.3,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,玉山,2.2,16.3,0.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,玉山,2.2,16.3,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,玉山,2.2,16.3,0.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,彭佳嶼,16.5,22.5,0.5
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,彭佳嶼,16.5,22.5,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,彭佳嶼,16.5,22.5,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,彭佳嶼,16.5,22.5,0.5
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,彭佳嶼,16.5,22.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,彭佳嶼,16.2,23.0,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,彭佳嶼,16.2,23.0,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,彭佳嶼,16.2,23.0,11.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,彭佳嶼,16.2,23.0,3.5
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,彭佳嶼,16.2,23.0,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,板橋,17.2,26.4,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,板橋,17.2,26.4,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,板橋,17.2,26.4,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,板橋,17.2,26.4,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,板橋,17.2,26.4,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,板橋,16.5,25.0,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,板橋,16.5,25.0,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,板橋,16.5,25.0,4.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,板橋,16.5,25.0,T
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,板橋,16.5,25.0,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,日月潭,14.9,24.0,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,日月潭,14.9,24.0,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,日月潭,14.9,24.0,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,日月潭,14.9,24.0,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,日月潭,14.9,24.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,日月潭,15.2,26.5,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,日月潭,15.2,26.5,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,日月潭,15.2,26.5,T
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,日月潭,15.2,26.5,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,日月潭,15.2,26.5,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071.0,60720.0,NaN,15.45,16.0,15.15,20.9,17.90,高雄,19.1,27.0,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071.0,60720.0,NaN,15.45,16.7,15.35,20.9,17.90,高雄,19.1,27.0,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071.0,60720.0,NaN,15.45,16.0,15.15,20.9,17.90,高雄,20.1,27.7,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071.0,60720.0,NaN,15.45,16.7,15.35,20.9,17.90,高雄,19.1,27.0,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071.0,60720.0,NaN,15.40,17.1,15.50,20.9,18.15,高雄,19.1,27.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,臺南,18.5,26.7,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,臺南,18.5,26.7,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,臺南,18.5,26.7,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,臺南,18.5,26.7,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,臺南,18.5,26.7,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,臺南,18.6,28.2,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,臺南,18.6,28.2,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,臺南,18.6,28.2,0.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,臺南,18.6,28.2,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,臺南,18.6,28.2,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,基隆,16.6,23.8,3.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,基隆,16.6,23.8,1.5
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,基隆,16.6,23.8,2.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,基隆,16.6,23.8,22.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,基隆,16.6,23.8,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,基隆,16.6,22.5,1.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,基隆,16.6,22.5,11.5
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,基隆,16.6,22.5,19.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,基隆,16.6,22.5,39.5
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,基隆,16.6,22.5,32.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,花蓮,18.6,25.5,14.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,花蓮,18.6,25.5,1.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,花蓮,18.6,25.5,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,花蓮,18.6,25.5,6.5
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,花蓮,18.6,25.5,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,花蓮,19.5,27.5,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,花蓮,19.5,27.5,3.5
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,花蓮,19.5,27.5,2.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,花蓮,19.5,27.5,T
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,花蓮,19.5,27.5,6.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,阿里山,6.8,13.2,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,阿里山,6.8,13.2,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,阿里山,6.8,13.2,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,阿里山,6.8,13.2,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,阿里山,6.8,13.2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,阿里山,7.8,16.9,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,阿里山,7.8,16.9,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,阿里山,7.8,16.9,0.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,阿里山,7.8,16.9,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,阿里山,7.8,16.9,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,嘉義,17.7,27.4,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,嘉義,17.7,27.4,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,嘉義,17.7,27.4,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,嘉義,17.7,27.4,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,嘉義,17.7,27.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,嘉義,17.6,29.3,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,嘉義,17.6,29.3,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,嘉義,17.6,29.3,0.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,嘉義,17.6,29.3,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,嘉義,17.6,29.3,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,新竹,16.9,24.2,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,新竹,16.9,24.2,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,新竹,16.9,24.2,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,新竹,16.9,24.2,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,新竹,16.9,24.2,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,新竹,16.4,23.3,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,新竹,16.4,23.3,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,新竹,16.4,23.3,T
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,新竹,16.4,23.3,T
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,新竹,16.4,23.3,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,金門,14.8,23.4,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,金門,14.8,23.4,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,金門,14.8,23.4,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,金門,14.8,23.4,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,金門,14.8,23.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,金門,14.7,24.9,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,金門,14.7,24.9,0.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,金門,14.7,24.9,0.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,金門,14.7,24.9,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,金門,14.7,24.9,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,恆春,21.3,26.7,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,恆春,21.3,26.7,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,恆春,21.3,26.7,T
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,恆春,21.3,26.7,3.5
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,恆春,21.3,26.7,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,恆春,22.1,29.8,0.5
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,恆春,22.1,29.8,T
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,恆春,22.1,29.8,0.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,恆春,22.1,29.8,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,恆春,22.1,29.8,0.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,臺北,17.2,25.8,T
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,臺北,17.2,25.8,T
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,臺北,17.2,25.8,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,臺北,17.2,25.8,T
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,臺北,17.2,25.8,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,臺北,16.6,24.8,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,臺北,16.6,24.8,T
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,臺北,16.6,24.8,5.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,臺北,16.6,24.8,0.5
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,臺北,16.6,24.8,0.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,鞍部,10.7,19.8,1.5
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,鞍部,10.7,19.8,2.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,鞍部,10.7,19.8,T
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,鞍部,10.7,19.8,2.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,鞍部,10.7,19.8,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,鞍部,10.5,19.1,1.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,鞍部,10.5,19.1,21.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,鞍部,10.5,19.1,19.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,鞍部,10.5,19.1,39.5
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,鞍部,10.5,19.1,35.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,臺東,20.2,26.5,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,臺東,20.2,26.5,0.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,臺東,20.2,26.5,T
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,臺東,20.2,26.5,2.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,臺東,20.2,26.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,臺東,20.9,28.5,T
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,臺東,20.9,28.5,T
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,臺東,20.9,28.5,T
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,臺東,20.9,28.5,T
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,臺東,20.9,28.5,0.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,竹子湖,12.7,21.4,0.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,竹子湖,12.7,21.4,0.5
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,竹子湖,12.7,21.4,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,竹子湖,12.7,21.4,T
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,竹子湖,12.7,21.4,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,竹子湖,12.2,19.9,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,竹子湖,12.2,19.9,15.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,竹子湖,12.2,19.9,20.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,竹子湖,12.2,19.9,40.5
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,竹子湖,12.2,19.9,26.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,新屋,16.5,22.2,T
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,新屋,16.5,22.2,T
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,新屋,16.5,22.2,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,新屋,16.5,22.2,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,新屋,16.5,22.2,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,新屋,16.2,23.7,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,新屋,16.2,23.7,T
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,新屋,16.2,23.7,1.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,新屋,16.2,23.7,3.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,新屋,16.2,23.7,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,蘇澳,17.3,26.6,5.5
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,蘇澳,17.3,26.6,1.0
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,蘇澳,17.3,26.6,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,蘇澳,17.3,26.6,4.5
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,蘇澳,17.3,26.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,蘇澳,16.9,26.6,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,蘇澳,16.9,26.6,136.0
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,蘇澳,16.9,26.6,27.0
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,蘇澳,16.9,26.6,54.5
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,蘇澳,16.9,26.6,69.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,淡水,16.5,26.4,T
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,淡水,16.5,26.4,T
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,淡水,16.5,26.4,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,淡水,16.5,26.4,0.0
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,淡水,16.5,26.4,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,淡水,15.8,23.3,0.0
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,淡水,15.8,23.3,T
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,淡水,15.8,23.3,2.5
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,淡水,15.8,23.3,2.5
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,淡水,15.8,23.3,0.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-01,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,大武,20.7,29.6,2.0
1,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-02,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,大武,20.7,29.6,T
2,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-03,362071,60720,NaN,15.45,16.0,15.15,20.9,17.90,大武,20.7,29.6,0.0
3,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-04,362071,60720,NaN,15.45,16.7,15.35,20.9,17.90,大武,20.7,29.6,1.5
4,34.5,38.0,1568627.0,32028103.0,114774.0,1583271.0,1789780.0,2022-01-05,362071,60720,NaN,15.40,17.1,15.50,20.9,18.15,大武,20.7,29.6,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-27,387890,83670,NaN,10.85,19.9,11.60,21.1,21.00,大武,21.7,28.4,0.5
361,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-28,387890,83670,NaN,11.05,19.9,11.68,21.1,21.00,大武,21.7,28.4,12.5
362,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-29,353700,91500,NaN,11.05,19.9,11.78,21.1,21.00,大武,21.7,28.4,T
363,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-30,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,大武,21.7,28.4,0.0
364,40.5,43.0,1592549.0,35037318.0,122636.0,1203140.0,990135.0,2022-12-31,353700,91500,NaN,11.20,19.9,11.78,21.1,21.00,大武,21.7,28.4,1.0

===================================== 2021 =====================================

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,澎湖,15.5,19.9,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,澎湖,15.5,19.9,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,澎湖,15.5,19.9,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,澎湖,15.5,19.9,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,澎湖,15.5,19.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,澎湖,19.2,25.1,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,澎湖,19.2,25.1,T
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,澎湖,19.2,25.1,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,澎湖,19.2,25.1,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,澎湖,19.2,25.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,東吉島,16.1,20.1,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,東吉島,16.1,20.1,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,東吉島,16.1,20.1,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,東吉島,16.1,20.1,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,東吉島,16.1,20.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,東吉島,20.1,24.6,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,東吉島,20.1,24.6,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,東吉島,20.1,24.6,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,東吉島,20.1,24.6,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,東吉島,20.1,24.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,馬祖,10.3,20.1,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,馬祖,10.3,20.1,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,馬祖,10.3,20.1,T
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,馬祖,10.3,20.1,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,馬祖,10.3,20.1,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,馬祖,13.5,23.0,0.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,馬祖,13.5,23.0,T
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,馬祖,13.5,23.0,T
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,馬祖,13.5,23.0,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,馬祖,13.5,23.0,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,成功,17.3,25.3,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,成功,17.3,25.3,1.5
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,成功,17.3,25.3,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,成功,17.3,25.3,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,成功,17.3,25.3,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,成功,20.0,26.2,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,成功,20.0,26.2,T
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,成功,20.0,26.2,T
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,成功,20.0,26.2,14.5
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,成功,20.0,26.2,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,宜蘭,15.3,25.2,T
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,宜蘭,15.3,25.2,0.5
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,宜蘭,15.3,25.2,T
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,宜蘭,15.3,25.2,0.5
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,宜蘭,15.3,25.2,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,宜蘭,17.7,26.6,6.5
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,宜蘭,17.7,26.6,1.5
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,宜蘭,17.7,26.6,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,宜蘭,17.7,26.6,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,宜蘭,17.7,26.6,0.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺中,16.0,30.4,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺中,16.0,30.4,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺中,16.0,30.4,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺中,16.0,30.4,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,臺中,16.0,30.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,臺中,18.8,28.2,1.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,臺中,18.8,28.2,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,臺中,18.8,28.2,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,臺中,18.8,28.2,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,臺中,18.8,28.2,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,蘭嶼,17.1,23.1,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,蘭嶼,17.1,23.1,0.5
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,蘭嶼,17.1,23.1,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,蘭嶼,17.1,23.1,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,蘭嶼,17.1,23.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,蘭嶼,19.4,25.6,3.5
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,蘭嶼,19.4,25.6,21.5
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,蘭嶼,19.4,25.6,3.5
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,蘭嶼,19.4,25.6,10.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,蘭嶼,19.4,25.6,3.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,玉山,-0.6,17.9,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,玉山,-0.6,17.9,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,玉山,-0.6,17.9,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,玉山,-0.6,17.9,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,玉山,-0.6,17.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,玉山,2.7,15.3,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,玉山,2.7,15.3,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,玉山,2.7,15.3,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,玉山,2.7,15.3,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,玉山,2.7,15.3,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,彭佳嶼,15.3,22.9,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,彭佳嶼,15.3,22.9,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,彭佳嶼,15.3,22.9,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,彭佳嶼,15.3,22.9,79.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,彭佳嶼,15.3,22.9,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,彭佳嶼,17.6,25.0,1.5
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,彭佳嶼,17.6,25.0,1.5
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,彭佳嶼,17.6,25.0,T
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,彭佳嶼,17.6,25.0,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,彭佳嶼,17.6,25.0,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,板橋,15.8,30.3,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,板橋,15.8,30.3,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,板橋,15.8,30.3,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,板橋,15.8,30.3,4.5
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,板橋,15.8,30.3,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,板橋,18.1,27.9,4.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,板橋,18.1,27.9,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,板橋,18.1,27.9,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,板橋,18.1,27.9,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,板橋,18.1,27.9,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,日月潭,12.9,24.8,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,日月潭,12.9,24.8,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,日月潭,12.9,24.8,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,日月潭,12.9,24.8,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,日月潭,12.9,24.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,日月潭,15.5,24.4,1.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,日月潭,15.5,24.4,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,日月潭,15.5,24.4,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,日月潭,15.5,24.4,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,日月潭,15.5,24.4,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,高雄,18.3,26.3,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,高雄,18.3,26.3,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,高雄,18.3,26.3,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,高雄,18.3,26.3,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,高雄,18.3,26.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,高雄,21.2,28.1,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,高雄,21.2,28.1,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,高雄,21.2,28.1,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,高雄,21.2,28.1,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,高雄,21.2,28.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺南,16.5,27.3,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺南,16.5,27.3,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺南,16.5,27.3,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺南,16.5,27.3,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,臺南,16.5,27.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,臺南,19.3,26.7,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,臺南,19.3,26.7,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,臺南,19.3,26.7,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,臺南,19.3,26.7,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,臺南,19.3,26.7,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,基隆,15.6,28.1,T
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,基隆,15.6,28.1,8.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,基隆,15.6,28.1,4.5
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,基隆,15.6,28.1,108.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,基隆,15.6,28.1,54.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,基隆,18.0,25.8,16.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,基隆,18.0,25.8,4.5
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,基隆,18.0,25.8,1.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,基隆,18.0,25.8,0.5
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,基隆,18.0,25.8,4.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,花蓮,16.6,23.8,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,花蓮,16.6,23.8,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,花蓮,16.6,23.8,5.5
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,花蓮,16.6,23.8,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,花蓮,16.6,23.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,花蓮,19.5,26.1,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,花蓮,19.5,26.1,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,花蓮,19.5,26.1,5.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,花蓮,19.5,26.1,1.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,花蓮,19.5,26.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,阿里山,5.7,14.9,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,阿里山,5.7,14.9,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,阿里山,5.7,14.9,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,阿里山,5.7,14.9,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,阿里山,5.7,14.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,阿里山,7.2,14.6,1.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,阿里山,7.2,14.6,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,阿里山,7.2,14.6,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,阿里山,7.2,14.6,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,阿里山,7.2,14.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,嘉義,15.7,29.6,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,嘉義,15.7,29.6,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,嘉義,15.7,29.6,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,嘉義,15.7,29.6,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,嘉義,15.7,29.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,嘉義,18.4,28.3,0.5
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,嘉義,18.4,28.3,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,嘉義,18.4,28.3,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,嘉義,18.4,28.3,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,嘉義,18.4,28.3,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,新竹,15.3,27.9,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,新竹,15.3,27.9,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,新竹,15.3,27.9,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,新竹,15.3,27.9,T
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,新竹,15.3,27.9,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,新竹,17.9,26.5,1.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,新竹,17.9,26.5,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,新竹,17.9,26.5,T
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,新竹,17.9,26.5,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,新竹,17.9,26.5,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,金門,13.3,28.5,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,金門,13.3,28.5,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,金門,13.3,28.5,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,金門,13.3,28.5,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,金門,13.3,28.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,金門,16.1,26.4,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,金門,16.1,26.4,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,金門,16.1,26.4,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,金門,16.1,26.4,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,金門,16.1,26.4,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,恆春,19.8,27.1,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,恆春,19.8,27.1,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,恆春,19.8,27.1,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,恆春,19.8,27.1,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,恆春,19.8,27.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,恆春,22.0,28.1,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,恆春,22.0,28.1,T
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,恆春,22.0,28.1,T
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,恆春,22.0,28.1,T
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,恆春,22.0,28.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺北,16.0,29.8,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺北,16.0,29.8,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺北,16.0,29.8,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺北,16.0,29.8,4.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,臺北,16.0,29.8,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,臺北,18.3,27.2,3.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,臺北,18.3,27.2,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,臺北,18.3,27.2,T
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,臺北,18.3,27.2,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,臺北,18.3,27.2,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,鞍部,9.0,22.7,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,鞍部,9.0,22.7,2.5
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,鞍部,9.0,22.7,11.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,鞍部,9.0,22.7,31.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,鞍部,9.0,22.7,30.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,鞍部,11.5,20.2,23.5
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,鞍部,11.5,20.2,3.5
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,鞍部,11.5,20.2,0.5
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,鞍部,11.5,20.2,0.5
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,鞍部,11.5,20.2,3.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺東,18.2,25.4,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺東,18.2,25.4,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺東,18.2,25.4,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,臺東,18.2,25.4,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,臺東,18.2,25.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,臺東,20.6,26.6,T
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,臺東,20.6,26.6,3.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,臺東,20.6,26.6,27.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,臺東,20.6,26.6,0.5
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,臺東,20.6,26.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,竹子湖,11.0,24.8,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,竹子湖,11.0,24.8,1.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,竹子湖,11.0,24.8,5.5
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,竹子湖,11.0,24.8,27.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,竹子湖,11.0,24.8,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,竹子湖,13.5,22.9,21.5
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,竹子湖,13.5,22.9,1.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,竹子湖,13.5,22.9,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,竹子湖,13.5,22.9,0.5
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,竹子湖,13.5,22.9,0.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,新屋,14.6,26.2,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,新屋,14.6,26.2,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,新屋,14.6,26.2,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,新屋,14.6,26.2,3.5
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,新屋,14.6,26.2,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,新屋,17.6,25.4,4.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,新屋,17.6,25.4,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,新屋,17.6,25.4,T
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,新屋,17.6,25.4,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,新屋,17.6,25.4,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,蘇澳,15.4,24.3,0.5
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,蘇澳,15.4,24.3,7.5
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,蘇澳,15.4,24.3,3.5
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,蘇澳,15.4,24.3,2.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,蘇澳,15.4,24.3,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,蘇澳,18.0,27.8,42.5
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,蘇澳,18.0,27.8,T
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,蘇澳,18.0,27.8,0.0
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,蘇澳,18.0,27.8,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,蘇澳,18.0,27.8,4.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,淡水,15.0,28.0,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,淡水,15.0,28.0,T
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,淡水,15.0,28.0,1.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,淡水,15.0,28.0,16.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,淡水,15.0,28.0,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,淡水,17.3,26.9,1.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,淡水,17.3,26.9,0.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,淡水,17.3,26.9,T
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,淡水,17.3,26.9,0.0
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,淡水,17.3,26.9,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-01,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,大武,19.2,26.0,0.0
1,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-02,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,大武,19.2,26.0,0.0
2,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-03,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,大武,19.2,26.0,0.0
3,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-04,297000,88600,35940.0,8.3,16.0,8.35,17.2,17.25,大武,19.2,26.0,0.0
4,24.5,32.0,1247145.0,33548211.0,121875.0,1331541.0,958692.0,2021-01-05,297000,88600,35940.0,8.5,16.2,8.50,17.2,17.25,大武,19.2,26.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-27,382887,52913,NaN,14.2,16.3,14.45,20.9,17.50,大武,21.5,27.0,0.0
361,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-28,382887,52913,NaN,14.3,16.5,14.55,20.9,17.70,大武,21.5,27.0,2.0
362,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-29,382887,52913,NaN,14.5,16.7,14.65,20.9,17.90,大武,21.5,27.0,0.5
363,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-30,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,大武,21.5,27.0,T
364,34.5,38.0,1508459.0,33574033.0,122899.0,1211918.0,715929.0,2021-12-31,382887,52913,NaN,14.8,16.7,14.85,20.9,17.90,大武,21.5,27.0,0.0

===================================== 2020 =====================================

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,澎湖,18.4,27.3,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,澎湖,18.4,27.3,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,澎湖,18.4,27.3,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,澎湖,18.4,27.3,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,澎湖,18.4,27.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,澎湖,18.5,23.9,T
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,澎湖,18.5,23.9,2.5
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,澎湖,18.5,23.9,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,澎湖,18.5,23.9,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,澎湖,18.5,23.9,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,東吉島,19.7,26.9,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,東吉島,19.7,26.9,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,東吉島,19.7,26.9,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,東吉島,19.7,26.9,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,東吉島,19.7,26.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,東吉島,20.1,25.2,2.5
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,東吉島,20.1,25.2,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,東吉島,20.1,25.2,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,東吉島,20.1,25.2,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,東吉島,20.1,25.2,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,馬祖,12.9,21.4,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,馬祖,12.9,21.4,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,馬祖,12.9,21.4,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,馬祖,12.9,21.4,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,馬祖,12.9,21.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,馬祖,12.9,21.4,0.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,馬祖,12.9,21.4,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,馬祖,12.9,21.4,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,馬祖,12.9,21.4,1.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,馬祖,12.9,21.4,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,成功,19.8,27.5,0.4
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,成功,19.8,27.5,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,成功,19.8,27.5,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,成功,19.8,27.5,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,成功,19.8,27.5,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,成功,20.3,27.7,15.5
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,成功,20.3,27.7,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,成功,20.3,27.7,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,成功,20.3,27.7,52.5
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,成功,20.3,27.7,3.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,宜蘭,18.3,27.9,1.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,宜蘭,18.3,27.9,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,宜蘭,18.3,27.9,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,宜蘭,18.3,27.9,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,宜蘭,18.3,27.9,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,宜蘭,18.0,26.6,T
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,宜蘭,18.0,26.6,2.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,宜蘭,18.0,26.6,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,宜蘭,18.0,26.6,0.5
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,宜蘭,18.0,26.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺中,18.0,29.0,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺中,18.0,29.0,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺中,18.0,29.0,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺中,18.0,29.0,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,臺中,18.0,29.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,臺中,19.5,28.5,2.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,臺中,19.5,28.5,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,臺中,19.5,28.5,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,臺中,19.5,28.5,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,臺中,19.5,28.5,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,蘭嶼,19.6,25.9,1.6
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,蘭嶼,19.6,25.9,1.8
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,蘭嶼,19.6,25.9,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,蘭嶼,19.6,25.9,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,蘭嶼,19.6,25.9,1.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,蘭嶼,19.7,25.1,166.5
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,蘭嶼,19.7,25.1,0.5
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,蘭嶼,19.7,25.1,10.5
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,蘭嶼,19.7,25.1,0.5
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,蘭嶼,19.7,25.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,玉山,1.8,18.9,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,玉山,1.8,18.9,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,玉山,1.8,18.9,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,玉山,1.8,18.9,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,玉山,1.8,18.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,玉山,0.9,16.1,0.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,玉山,0.9,16.1,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,玉山,0.9,16.1,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,玉山,0.9,16.1,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,玉山,0.9,16.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,彭佳嶼,17.0,24.4,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,彭佳嶼,17.0,24.4,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,彭佳嶼,17.0,24.4,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,彭佳嶼,17.0,24.4,1.8
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,彭佳嶼,17.0,24.4,11.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,彭佳嶼,17.8,24.6,T
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,彭佳嶼,17.8,24.6,0.5
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,彭佳嶼,17.8,24.6,T
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,彭佳嶼,17.8,24.6,1.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,彭佳嶼,17.8,24.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,板橋,17.3,27.6,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,板橋,17.3,27.6,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,板橋,17.3,27.6,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,板橋,17.3,27.6,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,板橋,17.3,27.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,板橋,17.9,25.8,1.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,板橋,17.9,25.8,2.5
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,板橋,17.9,25.8,T
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,板橋,17.9,25.8,15.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,板橋,17.9,25.8,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,日月潭,14.8,24.7,1.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,日月潭,14.8,24.7,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,日月潭,14.8,24.7,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,日月潭,14.8,24.7,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,日月潭,14.8,24.7,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,日月潭,16.8,28.2,2.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,日月潭,16.8,28.2,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,日月潭,16.8,28.2,T
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,日月潭,16.8,28.2,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,日月潭,16.8,28.2,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,高雄,20.9,29.0,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,高雄,20.9,29.0,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,高雄,20.9,29.0,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,高雄,20.9,29.0,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,高雄,20.9,29.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,高雄,22.3,28.6,4.5
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,高雄,22.3,28.6,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,高雄,22.3,28.6,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,高雄,22.3,28.6,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,高雄,22.3,28.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺南,19.0,29.4,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺南,19.0,29.4,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺南,19.0,29.4,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺南,19.0,29.4,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,臺南,19.0,29.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,臺南,20.1,29.4,0.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,臺南,20.1,29.4,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,臺南,20.1,29.4,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,臺南,20.1,29.4,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,臺南,20.1,29.4,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,基隆,17.2,26.5,5.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,基隆,17.2,26.5,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,基隆,17.2,26.5,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,基隆,17.2,26.5,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,基隆,17.2,26.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,基隆,18.0,23.1,3.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,基隆,18.0,23.1,2.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,基隆,18.0,23.1,T
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,基隆,18.0,23.1,9.5
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,基隆,18.0,23.1,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,花蓮,19.5,27.2,1.5
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,花蓮,19.5,27.2,3.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,花蓮,19.5,27.2,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,花蓮,19.5,27.2,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,花蓮,19.5,27.2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,花蓮,20.2,26.8,6.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,花蓮,20.2,26.8,0.5
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,花蓮,20.2,26.8,T
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,花蓮,20.2,26.8,1.5
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,花蓮,20.2,26.8,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,阿里山,6.8,16.7,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,阿里山,6.8,16.7,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,阿里山,6.8,16.7,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,阿里山,6.8,16.7,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,阿里山,6.8,16.7,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,阿里山,9.0,17.0,1.5
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,阿里山,9.0,17.0,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,阿里山,9.0,17.0,2.5
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,阿里山,9.0,17.0,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,阿里山,9.0,17.0,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,嘉義,18.2,29.9,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,嘉義,18.2,29.9,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,嘉義,18.2,29.9,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,嘉義,18.2,29.9,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,嘉義,18.2,29.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,嘉義,19.8,29.8,6.5
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,嘉義,19.8,29.8,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,嘉義,19.8,29.8,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,嘉義,19.8,29.8,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,嘉義,19.8,29.8,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,新竹,16.7,27.5,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,新竹,16.7,27.5,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,新竹,16.7,27.5,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,新竹,16.7,27.5,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,新竹,16.7,27.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,新竹,18.0,24.0,0.5
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,新竹,18.0,24.0,0.5
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,新竹,18.0,24.0,T
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,新竹,18.0,24.0,T
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,新竹,18.0,24.0,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,金門,15.6,25.5,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,金門,15.6,25.5,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,金門,15.6,25.5,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,金門,15.6,25.5,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,金門,15.6,25.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,金門,16.7,26.5,0.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,金門,16.7,26.5,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,金門,16.7,26.5,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,金門,16.7,26.5,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,金門,16.7,26.5,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,恆春,21.9,29.3,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,恆春,21.9,29.3,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,恆春,21.9,29.3,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,恆春,21.9,29.3,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,恆春,21.9,29.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,恆春,22.6,28.7,0.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,恆春,22.6,28.7,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,恆春,22.6,28.7,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,恆春,22.6,28.7,0.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,恆春,22.6,28.7,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺北,17.9,29.4,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺北,17.9,29.4,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺北,17.9,29.4,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺北,17.9,29.4,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,臺北,17.9,29.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,臺北,18.1,26.4,1.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,臺北,18.1,26.4,3.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,臺北,18.1,26.4,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,臺北,18.1,26.4,4.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,臺北,18.1,26.4,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,鞍部,11.7,22.1,2.5
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,鞍部,11.7,22.1,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,鞍部,11.7,22.1,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,鞍部,11.7,22.1,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,鞍部,11.7,22.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,鞍部,12.3,20.3,T
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,鞍部,12.3,20.3,5.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,鞍部,12.3,20.3,1.5
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,鞍部,12.3,20.3,26.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,鞍部,12.3,20.3,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺東,20.5,27.2,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺東,20.5,27.2,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺東,20.5,27.2,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,臺東,20.5,27.2,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,臺東,20.5,27.2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,臺東,21.1,27.2,1.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,臺東,21.1,27.2,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,臺東,21.1,27.2,T
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,臺東,21.1,27.2,1.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,臺東,21.1,27.2,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,竹子湖,13.1,23.6,1.5
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,竹子湖,13.1,23.6,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,竹子湖,13.1,23.6,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,竹子湖,13.1,23.6,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,竹子湖,13.1,23.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,竹子湖,13.4,21.8,0.5
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,竹子湖,13.4,21.8,7.5
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,竹子湖,13.4,21.8,1.5
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,竹子湖,13.4,21.8,12.5
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,竹子湖,13.4,21.8,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,新屋,16.5,26.4,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,新屋,16.5,26.4,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,新屋,16.5,26.4,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,新屋,16.5,26.4,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,新屋,16.5,26.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,新屋,17.4,22.7,0.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,新屋,17.4,22.7,0.5
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,新屋,17.4,22.7,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,新屋,17.4,22.7,1.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,新屋,17.4,22.7,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,蘇澳,18.1,26.0,1.5
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,蘇澳,18.1,26.0,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,蘇澳,18.1,26.0,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,蘇澳,18.1,26.0,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,蘇澳,18.1,26.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,蘇澳,17.8,23.9,T
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,蘇澳,17.8,23.9,4.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,蘇澳,17.8,23.9,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,蘇澳,17.8,23.9,0.5
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,蘇澳,17.8,23.9,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,淡水,16.8,26.8,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,淡水,16.8,26.8,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,淡水,16.8,26.8,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,淡水,16.8,26.8,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,淡水,16.8,26.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,淡水,17.4,23.6,T
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,淡水,17.4,23.6,1.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,淡水,17.4,23.6,0.0
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,淡水,17.4,23.6,8.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,淡水,17.4,23.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-01,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,大武,21.3,28.8,0.0
1,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-02,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,大武,21.3,28.8,0.0
2,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-03,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,大武,21.3,28.8,0.0
3,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-04,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.65,大武,21.3,28.8,0.0
4,27.5,34.0,1358328.0,30532400.0,112185.0,1403613.0,2684624.0,2020-01-05,394400,84500,20385.0,6.90,12.6,7.28,13.7,13.60,大武,21.3,28.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-27,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,大武,22.0,27.9,0.0
362,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-28,323900,69200,33498.0,7.85,15.4,8.28,16.6,16.66,大武,22.0,27.9,0.0
363,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-29,323900,69200,33498.0,7.90,15.6,8.28,16.8,16.66,大武,22.0,27.9,0.5
364,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-30,323900,69200,33498.0,8.00,15.8,8.28,17.0,16.76,大武,22.0,27.9,6.0
365,24.5,32.0,1407936.0,33803767.0,124295.0,1100058.0,791242.0,2020-12-31,323900,69200,33498.0,8.00,15.8,NaN,17.0,16.95,大武,22.0,27.9,0.0

===================================== 2019 =====================================

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,澎湖,18.0,26.8,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,澎湖,18.0,26.8,0.5
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,澎湖,18.0,26.8,2.5
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,澎湖,18.0,26.8,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,澎湖,18.0,26.8,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,澎湖,19.1,27.0,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,澎湖,19.1,27.0,1.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,澎湖,19.1,27.0,92.7
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,澎湖,19.1,27.0,9.6
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,澎湖,19.1,27.0,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,東吉島,19.6,25.8,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,東吉島,19.6,25.8,0.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,東吉島,19.6,25.8,0.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,東吉島,19.6,25.8,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,東吉島,19.6,25.8,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,東吉島,20.5,27.2,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,東吉島,20.5,27.2,1.8
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,東吉島,20.5,27.2,130.6
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,東吉島,20.5,27.2,7.7
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,東吉島,20.5,27.2,8.1

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,馬祖,11.5,24.2,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,馬祖,11.5,24.2,T
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,馬祖,11.5,24.2,0.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,馬祖,11.5,24.2,T
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,馬祖,11.5,24.2,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,馬祖,14.2,24.0,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,馬祖,14.2,24.0,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,馬祖,14.2,24.0,0.2
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,馬祖,14.2,24.0,12.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,馬祖,14.2,24.0,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,成功,20.3,27.5,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,成功,20.3,27.5,4.5
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,成功,20.3,27.5,0.7
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,成功,20.3,27.5,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,成功,20.3,27.5,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,成功,20.5,27.9,1.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,成功,20.5,27.9,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,成功,20.5,27.9,73.2
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,成功,20.5,27.9,4.8
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,成功,20.5,27.9,4.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,宜蘭,18.4,28.0,111.5
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,宜蘭,18.4,28.0,149.5
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,宜蘭,18.4,28.0,62.8
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,宜蘭,18.4,28.0,6.7
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,宜蘭,18.4,28.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,宜蘭,18.8,27.7,0.4
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,宜蘭,18.8,27.7,1.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,宜蘭,18.8,27.7,16.8
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,宜蘭,18.8,27.7,8.9
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,宜蘭,18.8,27.7,3.3

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,臺中,19.3,31.0,T
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,臺中,19.3,31.0,T
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,臺中,19.3,31.0,1.5
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,臺中,19.3,31.0,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,臺中,19.3,31.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,臺中,19.3,29.5,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,臺中,19.3,29.5,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺中,19.3,29.5,39.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺中,19.3,29.5,11.5
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺中,19.3,29.5,1.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,蘭嶼,19.7,27.0,9.2
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,蘭嶼,19.7,27.0,34.6
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,蘭嶼,19.7,27.0,11.3
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,蘭嶼,19.7,27.0,2.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,蘭嶼,19.7,27.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,蘭嶼,19.9,26.4,1.6
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,蘭嶼,19.9,26.4,6.7
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,蘭嶼,19.9,26.4,150.4
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,蘭嶼,19.9,26.4,24.3
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,蘭嶼,19.9,26.4,2.3

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,玉山,2.8,16.0,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,玉山,2.8,16.0,12.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,玉山,2.8,16.0,1.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,玉山,2.8,16.0,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,玉山,2.8,16.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,玉山,4.4,16.5,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,玉山,4.4,16.5,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,玉山,4.4,16.5,39.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,玉山,4.4,16.5,3.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,玉山,4.4,16.5,11.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,彭佳嶼,17.6,25.0,4.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,彭佳嶼,17.6,25.0,9.5
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,彭佳嶼,17.6,25.0,16.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,彭佳嶼,17.6,25.0,4.5
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,彭佳嶼,17.6,25.0,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,彭佳嶼,18.3,25.2,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,彭佳嶼,18.3,25.2,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,彭佳嶼,18.3,25.2,30.5
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,彭佳嶼,18.3,25.2,25.5
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,彭佳嶼,18.3,25.2,2.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,板橋,18.2,27.7,1.3
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,板橋,18.2,27.7,3.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,板橋,18.2,27.7,7.5
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,板橋,18.2,27.7,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,板橋,18.2,27.7,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,板橋,18.6,28.4,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,板橋,18.6,28.4,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,板橋,18.6,28.4,17.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,板橋,18.6,28.4,20.5
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,板橋,18.6,28.4,1.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,日月潭,16.3,26.0,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,日月潭,16.3,26.0,T
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,日月潭,16.3,26.0,2.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,日月潭,16.3,26.0,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,日月潭,16.3,26.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,日月潭,15.9,25.4,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,日月潭,15.9,25.4,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,日月潭,15.9,25.4,56.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,日月潭,15.9,25.4,23.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,日月潭,15.9,25.4,25.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,高雄,21.9,28.8,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,高雄,21.9,28.8,T
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,高雄,21.9,28.8,0.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,高雄,21.9,28.8,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,高雄,21.9,28.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,高雄,21.8,29.6,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,高雄,21.8,29.6,4.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,高雄,21.8,29.6,10.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,高雄,21.8,29.6,0.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,高雄,21.8,29.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,臺南,19.7,28.9,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,臺南,19.7,28.9,0.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,臺南,19.7,28.9,0.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,臺南,19.7,28.9,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,臺南,19.7,28.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,臺南,19.8,28.9,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,臺南,19.8,28.9,T
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺南,19.8,28.9,43.5
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺南,19.8,28.9,0.5
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺南,19.8,28.9,0.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,基隆,17.9,27.2,43.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,基隆,17.9,27.2,45.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,基隆,17.9,27.2,40.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,基隆,17.9,27.2,2.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,基隆,17.9,27.2,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,基隆,18.6,28.3,T
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,基隆,18.6,28.3,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,基隆,18.6,28.3,15.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,基隆,18.6,28.3,30.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,基隆,18.6,28.3,41.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,花蓮,20.0,26.8,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,花蓮,20.0,26.8,10.5
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,花蓮,20.0,26.8,4.5
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,花蓮,20.0,26.8,0.5
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,花蓮,20.0,26.8,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,花蓮,20.2,27.1,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,花蓮,20.2,27.1,6.5
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,花蓮,20.2,27.1,37.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,花蓮,20.2,27.1,11.5
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,花蓮,20.2,27.1,11.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,阿里山,7.4,15.6,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,阿里山,7.4,15.6,5.4
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,阿里山,7.4,15.6,0.6
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,阿里山,7.4,15.6,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,阿里山,7.4,15.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,阿里山,8.8,18.2,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,阿里山,8.8,18.2,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,阿里山,8.8,18.2,54.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,阿里山,8.8,18.2,5.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,阿里山,8.8,18.2,14.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,嘉義,19.2,30.9,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,嘉義,19.2,30.9,T
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,嘉義,19.2,30.9,0.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,嘉義,19.2,30.9,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,嘉義,19.2,30.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,嘉義,19.1,30.0,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,嘉義,19.1,30.0,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,嘉義,19.1,30.0,76.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,嘉義,19.1,30.0,3.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,嘉義,19.1,30.0,5.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,新竹,17.7,25.1,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,新竹,17.7,25.1,T
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,新竹,17.7,25.1,2.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,新竹,17.7,25.1,T
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,新竹,17.7,25.1,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,新竹,18.3,26.9,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,新竹,18.3,26.9,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,新竹,18.3,26.9,33.5
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,新竹,18.3,26.9,23.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,新竹,18.3,26.9,0.2

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,金門,15.5,23.8,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,金門,15.5,23.8,T
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,金門,15.5,23.8,4.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,金門,15.5,23.8,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,金門,15.5,23.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,金門,16.8,25.9,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,金門,16.8,25.9,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,金門,16.8,25.9,40.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,金門,16.8,25.9,14.5
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,金門,16.8,25.9,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,恆春,22.6,29.8,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,恆春,22.6,29.8,0.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,恆春,22.6,29.8,1.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,恆春,22.6,29.8,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,恆春,22.6,29.8,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,恆春,22.4,29.5,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,恆春,22.4,29.5,3.5
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,恆春,22.4,29.5,3.5
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,恆春,22.4,29.5,0.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,恆春,22.4,29.5,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,臺北,18.5,28.6,2.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,臺北,18.5,28.6,5.7
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,臺北,18.5,28.6,6.4
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,臺北,18.5,28.6,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,臺北,18.5,28.6,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,臺北,19.1,29.5,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,臺北,19.1,29.5,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺北,19.1,29.5,15.5
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺北,19.1,29.5,16.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺北,19.1,29.5,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,鞍部,12.3,21.8,46.5
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,鞍部,12.3,21.8,41.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,鞍部,12.3,21.8,46.5
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,鞍部,12.3,21.8,1.5
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,鞍部,12.3,21.8,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,鞍部,12.8,22.6,4.9
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,鞍部,12.8,22.6,0.9
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,鞍部,12.8,22.6,27.5
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,鞍部,12.8,22.6,37.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,鞍部,12.8,22.6,29.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,臺東,21.1,28.3,T
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,臺東,21.1,28.3,3.5
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,臺東,21.1,28.3,T
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,臺東,21.1,28.3,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,臺東,21.1,28.3,5.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,臺東,21.1,27.8,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,臺東,21.1,27.8,0.8
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺東,21.1,27.8,66.0
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺東,21.1,27.8,1.9
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,臺東,21.1,27.8,T

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,竹子湖,13.9,23.9,33.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,竹子湖,13.9,23.9,24.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,竹子湖,13.9,23.9,29.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,竹子湖,13.9,23.9,1.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,竹子湖,13.9,23.9,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,竹子湖,14.3,23.1,10.5
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,竹子湖,14.3,23.1,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,竹子湖,14.3,23.1,23.7
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,竹子湖,14.3,23.1,34.8
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,竹子湖,14.3,23.1,45.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,新屋,17.1,24.0,T
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,新屋,17.1,24.0,2.3
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,新屋,17.1,24.0,4.9
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,新屋,17.1,24.0,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,新屋,17.1,24.0,5.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,新屋,18.0,27.5,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,新屋,18.0,27.5,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,新屋,18.0,27.5,36.1
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,新屋,18.0,27.5,24.4
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,新屋,18.0,27.5,3.4

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,蘇澳,18.2,27.3,190.5
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,蘇澳,18.2,27.3,204.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,蘇澳,18.2,27.3,177.5
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,蘇澳,18.2,27.3,23.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,蘇澳,18.2,27.3,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,蘇澳,18.6,25.9,7.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,蘇澳,18.6,25.9,0.5
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,蘇澳,18.6,25.9,15.5
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,蘇澳,18.6,25.9,13.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,蘇澳,18.6,25.9,38.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,淡水,17.6,27.3,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,淡水,17.6,27.3,6.0
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,淡水,17.6,27.3,23.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,淡水,17.6,27.3,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,淡水,17.6,27.3,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,淡水,18.0,26.8,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,淡水,18.0,26.8,0.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,淡水,18.0,26.8,20.5
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,淡水,18.0,26.8,25.5
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,淡水,18.0,26.8,3.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-01,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,大武,21.9,31.5,0.0
1,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-02,329600,35800,35701,7.40,12.30,7.93,13.50,13.44,大武,21.9,31.5,0.5
2,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-03,329600,35800,35701,7.35,12.30,7.90,13.50,13.45,大武,21.9,31.5,0.0
3,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-04,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,大武,21.9,31.5,0.0
4,33.5,34.0,1751620.0,28287430.0,94427.0,1549147.0,1380962.0,2019-01-05,329600,35800,35701,7.35,12.30,7.87,13.50,13.45,大武,21.9,31.5,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-27,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,大武,21.8,28.5,0.0
361,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-28,349400,112000,29000,6.88,12.65,7.26,13.75,13.68,大武,21.8,28.5,6.0
362,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-29,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,大武,21.8,28.5,37.6
363,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-30,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,大武,21.8,28.5,0.0
364,27.5,34.0,1209823.0,32805865.0,120704.0,934644.0,790006.0,2019-12-31,349400,112000,29000,6.90,12.60,7.26,13.70,13.65,大武,21.8,28.5,0.0

===================================== 2018 =====================================

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,澎湖,17.6,24.2,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,澎湖,17.6,24.2,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,澎湖,17.6,24.2,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,澎湖,17.6,24.2,7.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,澎湖,17.6,24.2,2.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,澎湖,20.7,28.6,T
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,澎湖,20.7,28.6,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,澎湖,20.7,28.6,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,澎湖,20.7,28.6,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,澎湖,20.7,28.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,東吉島,18.6,26.0,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,東吉島,18.6,26.0,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,東吉島,18.6,26.0,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,東吉島,18.6,26.0,7.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,東吉島,18.6,26.0,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,東吉島,21.6,27.8,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,東吉島,21.6,27.8,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,東吉島,21.6,27.8,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,東吉島,21.6,27.8,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,東吉島,21.6,27.8,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,馬祖,10.7,21.8,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,馬祖,10.7,21.8,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,馬祖,10.7,21.8,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,馬祖,10.7,21.8,0.1
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,馬祖,10.7,21.8,1.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,馬祖,14.0,24.1,T
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,馬祖,14.0,24.1,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,馬祖,14.0,24.1,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,馬祖,14.0,24.1,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,馬祖,14.0,24.1,1.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,成功,18.6,25.7,0.8
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,成功,18.6,25.7,1.4
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,成功,18.6,25.7,0.2
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,成功,18.6,25.7,2.1
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,成功,18.6,25.7,11.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,成功,21.1,28.9,1.5
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,成功,21.1,28.9,2.2
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,成功,21.1,28.9,7.9
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,成功,21.1,28.9,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,成功,21.1,28.9,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,宜蘭,16.7,25.3,3.5
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,宜蘭,16.7,25.3,3.2
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,宜蘭,16.7,25.3,1.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,宜蘭,16.7,25.3,0.1
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,宜蘭,16.7,25.3,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,宜蘭,19.3,29.0,4.5
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,宜蘭,19.3,29.0,2.5
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,宜蘭,19.3,29.0,3.1
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,宜蘭,19.3,29.0,56.5
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,宜蘭,19.3,29.0,38.8

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺中,17.3,27.2,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺中,17.3,27.2,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺中,17.3,27.2,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,臺中,17.3,27.2,4.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,臺中,17.3,27.2,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,臺中,20.8,31.7,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,臺中,20.8,31.7,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺中,20.8,31.7,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺中,20.8,31.7,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺中,20.8,31.7,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,蘭嶼,18.2,23.0,9.2
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,蘭嶼,18.2,23.0,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,蘭嶼,18.2,23.0,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,蘭嶼,18.2,23.0,6.7
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,蘭嶼,18.2,23.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,蘭嶼,20.6,25.5,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,蘭嶼,20.6,25.5,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,蘭嶼,20.6,25.5,2.1
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,蘭嶼,20.6,25.5,6.3
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,蘭嶼,20.6,25.5,13.2

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,玉山,0.5,12.8,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,玉山,0.5,12.8,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,玉山,0.5,12.8,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,玉山,0.5,12.8,17.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,玉山,0.5,12.8,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,玉山,5.1,16.6,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,玉山,5.1,16.6,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,玉山,5.1,16.6,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,玉山,5.1,16.6,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,玉山,5.1,16.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,彭佳嶼,16.0,22.4,T
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,彭佳嶼,16.0,22.4,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,彭佳嶼,16.0,22.4,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,彭佳嶼,16.0,22.4,1.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,彭佳嶼,16.0,22.4,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,彭佳嶼,18.7,27.8,2.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,彭佳嶼,18.7,27.8,1.5
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,彭佳嶼,18.7,27.8,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,彭佳嶼,18.7,27.8,1.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,彭佳嶼,18.7,27.8,6.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,板橋,16.6,25.7,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,板橋,16.6,25.7,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,板橋,16.6,25.7,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,板橋,16.6,25.7,0.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,板橋,16.6,25.7,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,板橋,19.1,30.1,9.5
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,板橋,19.1,30.1,T
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,板橋,19.1,30.1,T
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,板橋,19.1,30.1,T
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,板橋,19.1,30.1,1.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,日月潭,14.8,25.5,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,日月潭,14.8,25.5,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,日月潭,14.8,25.5,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,日月潭,14.8,25.5,2.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,日月潭,14.8,25.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,日月潭,17.8,27.7,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,日月潭,17.8,27.7,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,日月潭,17.8,27.7,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,日月潭,17.8,27.7,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,日月潭,17.8,27.7,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,高雄,20.4,29.3,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,高雄,20.4,29.3,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,高雄,20.4,29.3,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,高雄,20.4,29.3,7.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,高雄,20.4,29.3,11.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,高雄,23.4,32.4,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,高雄,23.4,32.4,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,高雄,23.4,32.4,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,高雄,23.4,32.4,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,高雄,23.4,32.4,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺南,18.1,28.2,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺南,18.1,28.2,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺南,18.1,28.2,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,臺南,18.1,28.2,16.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,臺南,18.1,28.2,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,臺南,21.6,30.5,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,臺南,21.6,30.5,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺南,21.6,30.5,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺南,21.6,30.5,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺南,21.6,30.5,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,基隆,16.3,24.3,1.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,基隆,16.3,24.3,0.5
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,基隆,16.3,24.3,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,基隆,16.3,24.3,T
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,基隆,16.3,24.3,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,基隆,19.1,29.8,14.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,基隆,19.1,29.8,6.5
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,基隆,19.1,29.8,1.5
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,基隆,19.1,29.8,28.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,基隆,19.1,29.8,76.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,花蓮,18.2,24.9,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,花蓮,18.2,24.9,6.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,花蓮,18.2,24.9,T
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,花蓮,18.2,24.9,1.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,花蓮,18.2,24.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,花蓮,21.0,29.2,T
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,花蓮,21.0,29.2,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,花蓮,21.0,29.2,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,花蓮,21.0,29.2,T
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,花蓮,21.0,29.2,1.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,阿里山,8.4,16.7,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,阿里山,8.4,16.7,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,阿里山,8.4,16.7,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,阿里山,8.4,16.7,11.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,阿里山,8.4,16.7,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,阿里山,10.0,18.3,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,阿里山,10.0,18.3,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,阿里山,10.0,18.3,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,阿里山,10.0,18.3,0.1
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,阿里山,10.0,18.3,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,嘉義,17.4,27.8,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,嘉義,17.4,27.8,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,嘉義,17.4,27.8,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,嘉義,17.4,27.8,5.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,嘉義,17.4,27.8,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,嘉義,20.7,31.6,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,嘉義,20.7,31.6,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,嘉義,20.7,31.6,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,嘉義,20.7,31.6,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,嘉義,20.7,31.6,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,新竹,16.3,25.5,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,新竹,16.3,25.5,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,新竹,16.3,25.5,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,新竹,16.3,25.5,0.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,新竹,16.3,25.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,新竹,19.1,29.8,0.5
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,新竹,19.1,29.8,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,新竹,19.1,29.8,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,新竹,19.1,29.8,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,新竹,19.1,29.8,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,金門,14.2,25.5,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,金門,14.2,25.5,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,金門,14.2,25.5,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,金門,14.2,25.5,0.1
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,金門,14.2,25.5,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,金門,17.2,27.0,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,金門,17.2,27.0,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,金門,17.2,27.0,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,金門,17.2,27.0,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,金門,17.2,27.0,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,恆春,21.4,28.3,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,恆春,21.4,28.3,T
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,恆春,21.4,28.3,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,恆春,21.4,28.3,0.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,恆春,21.4,28.3,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,恆春,23.6,30.9,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,恆春,23.6,30.9,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,恆春,23.6,30.9,0.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,恆春,23.6,30.9,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,恆春,23.6,30.9,0.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺北,16.9,26.6,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺北,16.9,26.6,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺北,16.9,26.6,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,臺北,16.9,26.6,0.3
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,臺北,16.9,26.6,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,臺北,19.5,30.5,6.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,臺北,19.5,30.5,0.4
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺北,19.5,30.5,0.5
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺北,19.5,30.5,0.5
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺北,19.5,30.5,1.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,鞍部,10.6,20.7,4.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,鞍部,10.6,20.7,0.5
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,鞍部,10.6,20.7,0.7
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,鞍部,10.6,20.7,0.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,鞍部,10.6,20.7,9.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,鞍部,13.5,24.2,58.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,鞍部,13.5,24.2,56.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,鞍部,13.5,24.2,29.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,鞍部,13.5,24.2,76.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,鞍部,13.5,24.2,54.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺東,19.1,25.4,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺東,19.1,25.4,0.1
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,臺東,19.1,25.4,T
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,臺東,19.1,25.4,4.2
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,臺東,19.1,25.4,10.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,臺東,22.0,29.6,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,臺東,22.0,29.6,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺東,22.0,29.6,T
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺東,22.0,29.6,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,臺東,22.0,29.6,0.2

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,竹子湖,12.3,21.5,1.2
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,竹子湖,12.3,21.5,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,竹子湖,12.3,21.5,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,竹子湖,12.3,21.5,0.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,竹子湖,12.3,21.5,6.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,竹子湖,15.0,25.0,67.2
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,竹子湖,15.0,25.0,85.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,竹子湖,15.0,25.0,49.5
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,竹子湖,15.0,25.0,51.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,竹子湖,15.0,25.0,56.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,新屋,15.9,26.2,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,新屋,15.9,26.2,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,新屋,15.9,26.2,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,新屋,15.9,26.2,0.1
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,新屋,15.9,26.2,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,新屋,18.5,30.8,3.3
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,新屋,18.5,30.8,0.4
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,新屋,18.5,30.8,0.5
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,新屋,18.5,30.8,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,新屋,18.5,30.8,0.2

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,蘇澳,16.6,23.6,5.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,蘇澳,16.6,23.6,10.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,蘇澳,16.6,23.6,6.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,蘇澳,16.6,23.6,5.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,蘇澳,16.6,23.6,15.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,蘇澳,19.0,28.1,40.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,蘇澳,19.0,28.1,105.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,蘇澳,19.0,28.1,59.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,蘇澳,19.0,28.1,99.5
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,蘇澳,19.0,28.1,165.5

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,淡水,16.6,25.3,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,淡水,16.6,25.3,0.0
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,淡水,16.6,25.3,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,淡水,16.6,25.3,0.0
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,淡水,16.6,25.3,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,淡水,18.6,28.7,38.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,淡水,18.6,28.7,13.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,淡水,18.6,28.7,9.0
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,淡水,18.6,28.7,2.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,淡水,18.6,28.7,2.0

,egg_TaijinPrice,Duckegg_TNN_TaijinPrice,入中雞雛數,產蛋隻數,均 日 產蛋箱數,淘汰隻數,目 前 換羽隻數,Date,WhiteChickQuantity,RedChickQuantity,ImportChickenQuantity,玉米粒,黃豆粉,玉米粉,脫殼豆粉,高蛋白豆粉,StationName,AirTemperatureMean,AirTemperatureMax,Precipitation
0,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-01,245600,84800,0,6.1,12.15,6.65,13.30,13.21,大武,20.0,31.2,0.0
1,24.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-02,245600,84800,0,6.1,12.15,6.65,13.30,13.21,大武,20.0,31.2,3.5
2,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-03,245600,84800,0,6.1,12.15,6.65,13.30,13.21,大武,20.0,31.2,0.0
3,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-04,245600,84800,0,6.1,12.15,6.63,13.30,13.21,大武,20.0,31.2,4.5
4,26.5,34.0,1160830.0,31170982.0,114908.0,866824.0,633700.0,2018-01-05,245600,84800,0,6.1,12.15,6.63,13.30,13.20,大武,20.0,31.2,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-27,306800,52800,0,7.4,12.35,7.98,13.55,13.41,大武,22.7,29.0,0.0
361,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-28,306800,52800,0,7.4,12.35,7.95,13.55,13.41,大武,22.7,29.0,0.0
362,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-29,321400,39900,0,7.4,12.35,7.95,13.55,13.41,大武,22.7,29.0,0.1
363,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-30,321400,39900,0,7.4,12.35,7.95,13.55,13.41,大武,22.7,29.0,0.0
364,33.5,34.0,1265184.0,29069345.0,94794.0,922436.0,893790.0,2018-12-31,321400,39900,0,7.4,12.35,7.95,13.55,13.41,大武,22.7,29.0,0.0

# Store data by location

In [5]:
import os

data_folder = f'./concat-data'
if not os.path.isdir(data_folder):
    os.mkdir(data_folder)

for location in locations:
    location_folder = f'{data_folder}/{location}'
    if not os.path.isdir(location_folder):
        os.mkdir(location_folder)

    for year in years:
        for loc, df in full_dataset_by_year_location_dict[year].items():
            if loc == location:
                full_dataset_by_year_location_dict[year][loc].to_csv(f'{location_folder}/{year}.csv', index=False)